from lib.framework import ControllerPublic
from lib.framework import json_decode
from lib.framework import page
from lib.framework import returnAs
from lib.framework import t
from requests      import get
from datetime      import datetime

'''
// example output
{
   "current_condition":[
      {
         "FeelsLikeC":"7",
         "FeelsLikeF":"44",
         "cloudcover":"0",
         "humidity":"48",
         "localObsDateTime":"2025-03-14 11:41 AM",
         "observation_time":"03:41 PM",
         "precipInches":"0.0",
         "precipMM":"0.0",
         "pressure":"1020",
         "pressureInches":"30",
         "temp_C":"8",
         "temp_F":"47",
         "uvIndex":"3",
         "visibility":"16",
         "visibilityMiles":"9",
         "weatherCode":"113",
         "weatherDesc":[
            {
               "value":"Sunny"
            }
         ],
         "weatherIconUrl":[
            {
               "value":""
            }
         ],
         "winddir16Point":"S",
         "winddirDegree":"186",
         "windspeedKmph":"10",
         "windspeedMiles":"6"
      }
   ],
   "nearest_area":[
      {
         "areaName":[
            {
               "value":"Middlebury"
            }
         ],
         "country":[
            {
               "value":"United States of America"
            }
         ],
         "latitude":"44.015",
         "longitude":"-73.168",
         "population":"8862",
         "region":[
            {
               "value":"Vermont"
            }
         ],
         "weatherUrl":[
            {
               "value":""
            }
         ]
      }
   ],
   "request":[
      {
         "query":"Lat 43.98 and Lon -73.01",
         "type":"LatLon"
      }
   ],
   "weather":[
      {
         "astronomy":[
            {
               "moon_illumination":"100",
               "moon_phase":"Full Moon",
               "moonrise":"07:36 PM",
               "moonset":"07:16 AM",
               "sunrise":"07:07 AM",
               "sunset":"06:59 PM"
            }
         ],
         "avgtempC":"6",
         "avgtempF":"44",
         "date":"2025-03-14",
         "hourly":[
            {
               "DewPointC":"-2",
               "DewPointF":"28",
               "FeelsLikeC":"0",
               "FeelsLikeF":"32",
               "HeatIndexC":"3",
               "HeatIndexF":"37",
               "WindChillC":"0",
               "WindChillF":"32",
               "WindGustKmph":"11",
               "WindGustMiles":"7",
               "chanceoffog":"0",
               "chanceoffrost":"76",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"94",
               "chanceofsnow":"0",
               "chanceofsunshine":"92",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"2",
               "diffRad":"0.0",
               "humidity":"69",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1020",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"3",
               "tempF":"37",
               "time":"0",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Clear "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"200",
               "windspeedKmph":"5",
               "windspeedMiles":"3"
            },
            {
               "DewPointC":"-3",
               "DewPointF":"27",
               "FeelsLikeC":"-2",
               "FeelsLikeF":"29",
               "HeatIndexC":"1",
               "HeatIndexF":"34",
               "WindChillC":"-2",
               "WindChillF":"29",
               "WindGustKmph":"12",
               "WindGustMiles":"8",
               "chanceoffog":"0",
               "chanceoffrost":"96",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"88",
               "chanceofsnow":"0",
               "chanceofsunshine":"89",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"0",
               "diffRad":"0.0",
               "humidity":"77",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1020",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"1",
               "tempF":"34",
               "time":"300",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Clear "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"201",
               "windspeedKmph":"6",
               "windspeedMiles":"4"
            },
            {
               "DewPointC":"-3",
               "DewPointF":"27",
               "FeelsLikeC":"-3",
               "FeelsLikeF":"27",
               "HeatIndexC":"-0",
               "HeatIndexF":"32",
               "WindChillC":"-3",
               "WindChillF":"27",
               "WindGustKmph":"13",
               "WindGustMiles":"8",
               "chanceoffog":"0",
               "chanceoffrost":"97",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"85",
               "chanceofsnow":"0",
               "chanceofsunshine":"87",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"0",
               "diffRad":"0.0",
               "humidity":"83",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1020",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"-0",
               "tempF":"32",
               "time":"600",
               "uvIndex":"0",
               "visibility":"2",
               "visibilityMiles":"1",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Clear "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"204",
               "windspeedKmph":"6",
               "windspeedMiles":"4"
            },
            {
               "DewPointC":"-2",
               "DewPointF":"28",
               "FeelsLikeC":"1",
               "FeelsLikeF":"33",
               "HeatIndexC":"3",
               "HeatIndexF":"38",
               "WindChillC":"1",
               "WindChillF":"33",
               "WindGustKmph":"10",
               "WindGustMiles":"6",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"83",
               "chanceofsnow":"0",
               "chanceofsunshine":"85",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"0",
               "diffRad":"44.8",
               "humidity":"72",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1021",
               "pressureInches":"30",
               "shortRad":"206.6",
               "tempC":"3",
               "tempF":"38",
               "time":"900",
               "uvIndex":"1",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"192",
               "windspeedKmph":"8",
               "windspeedMiles":"5"
            },
            {
               "DewPointC":"2",
               "DewPointF":"36",
               "FeelsLikeC":"9",
               "FeelsLikeF":"48",
               "HeatIndexC":"10",
               "HeatIndexF":"51",
               "WindChillC":"9",
               "WindChillF":"48",
               "WindGustKmph":"11",
               "WindGustMiles":"7",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"80",
               "chanceofsnow":"0",
               "chanceofsunshine":"88",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"0",
               "diffRad":"61.7",
               "humidity":"53",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1021",
               "pressureInches":"30",
               "shortRad":"457.5",
               "tempC":"10",
               "tempF":"51",
               "time":"1200",
               "uvIndex":"4",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"177",
               "windspeedKmph":"9",
               "windspeedMiles":"6"
            },
            {
               "DewPointC":"4",
               "DewPointF":"38",
               "FeelsLikeC":"11",
               "FeelsLikeF":"53",
               "HeatIndexC":"13",
               "HeatIndexF":"55",
               "WindChillC":"11",
               "WindChillF":"53",
               "WindGustKmph":"14",
               "WindGustMiles":"9",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"81",
               "chanceofsnow":"0",
               "chanceofsunshine":"94",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"8",
               "diffRad":"78.8",
               "humidity":"52",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1019",
               "pressureInches":"30",
               "shortRad":"678.7",
               "tempC":"13",
               "tempF":"55",
               "time":"1500",
               "uvIndex":"3",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"188",
               "windspeedKmph":"12",
               "windspeedMiles":"8"
            },
            {
               "DewPointC":"6",
               "DewPointF":"42",
               "FeelsLikeC":"12",
               "FeelsLikeF":"54",
               "HeatIndexC":"13",
               "HeatIndexF":"56",
               "WindChillC":"12",
               "WindChillF":"54",
               "WindGustKmph":"13",
               "WindGustMiles":"8",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"88",
               "chanceofsnow":"0",
               "chanceofsunshine":"93",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"0",
               "diffRad":"85.3",
               "humidity":"57",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1018",
               "pressureInches":"30",
               "shortRad":"459.9",
               "tempC":"13",
               "tempF":"56",
               "time":"1800",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Sunny"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"194",
               "windspeedKmph":"8",
               "windspeedMiles":"5"
            },
            {
               "DewPointC":"2",
               "DewPointF":"35",
               "FeelsLikeC":"7",
               "FeelsLikeF":"45",
               "HeatIndexC":"9",
               "HeatIndexF":"48",
               "WindChillC":"7",
               "WindChillF":"45",
               "WindGustKmph":"14",
               "WindGustMiles":"8",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"0",
               "chanceofrain":"0",
               "chanceofremdry":"93",
               "chanceofsnow":"0",
               "chanceofsunshine":"87",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"22",
               "diffRad":"0.0",
               "humidity":"60",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1017",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"9",
               "tempF":"48",
               "time":"2100",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"113",
               "weatherDesc":[
                  {
                     "value":"Clear "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"206",
               "windspeedKmph":"6",
               "windspeedMiles":"4"
            }
         ],
         "maxtempC":"14",
         "maxtempF":"57",
         "mintempC":"-1",
         "mintempF":"31",
         "sunHour":"11.0",
         "totalSnow_cm":"0.0",
         "uvIndex":"1"
      },
      {
         "astronomy":[
            {
               "moon_illumination":"100",
               "moon_phase":"Waning Gibbous",
               "moonrise":"08:39 PM",
               "moonset":"07:32 AM",
               "sunrise":"07:05 AM",
               "sunset":"07:00 PM"
            }
         ],
         "avgtempC":"6",
         "avgtempF":"43",
         "date":"2025-03-15",
         "hourly":[
            {
               "DewPointC":"1",
               "DewPointF":"34",
               "FeelsLikeC":"4",
               "FeelsLikeF":"39",
               "HeatIndexC":"7",
               "HeatIndexF":"44",
               "WindChillC":"4",
               "WindChillF":"39",
               "WindGustKmph":"17",
               "WindGustMiles":"11",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"94",
               "chanceofrain":"0",
               "chanceofremdry":"88",
               "chanceofsnow":"0",
               "chanceofsunshine":"10",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"0.0",
               "humidity":"66",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1017",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"7",
               "tempF":"44",
               "time":"0",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"202",
               "windspeedKmph":"8",
               "windspeedMiles":"5"
            },
            {
               "DewPointC":"3",
               "DewPointF":"38",
               "FeelsLikeC":"2",
               "FeelsLikeF":"35",
               "HeatIndexC":"5",
               "HeatIndexF":"41",
               "WindChillC":"2",
               "WindChillF":"35",
               "WindGustKmph":"19",
               "WindGustMiles":"12",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"92",
               "chanceofrain":"0",
               "chanceofremdry":"93",
               "chanceofsnow":"0",
               "chanceofsunshine":"14",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"88",
               "diffRad":"0.0",
               "humidity":"90",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1017",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"5",
               "tempF":"41",
               "time":"300",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"197",
               "windspeedKmph":"9",
               "windspeedMiles":"6"
            },
            {
               "DewPointC":"3",
               "DewPointF":"37",
               "FeelsLikeC":"-0",
               "FeelsLikeF":"32",
               "HeatIndexC":"3",
               "HeatIndexF":"38",
               "WindChillC":"-0",
               "WindChillF":"32",
               "WindGustKmph":"20",
               "WindGustMiles":"12",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"84",
               "chanceofrain":"0",
               "chanceofremdry":"85",
               "chanceofsnow":"0",
               "chanceofsunshine":"16",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"87",
               "diffRad":"0.0",
               "humidity":"97",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1017",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"3",
               "tempF":"38",
               "time":"600",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"119",
               "weatherDesc":[
                  {
                     "value":"Cloudy "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"196",
               "windspeedKmph":"10",
               "windspeedMiles":"6"
            },
            {
               "DewPointC":"3",
               "DewPointF":"37",
               "FeelsLikeC":"-0",
               "FeelsLikeF":"31",
               "HeatIndexC":"3",
               "HeatIndexF":"38",
               "WindChillC":"-0",
               "WindChillF":"31",
               "WindGustKmph":"15",
               "WindGustMiles":"9",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"84",
               "chanceofrain":"0",
               "chanceofremdry":"81",
               "chanceofsnow":"0",
               "chanceofsunshine":"7",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"98",
               "diffRad":"58.8",
               "humidity":"97",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1018",
               "pressureInches":"30",
               "shortRad":"196.7",
               "tempC":"3",
               "tempF":"38",
               "time":"900",
               "uvIndex":"1",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"191",
               "windspeedKmph":"13",
               "windspeedMiles":"8"
            },
            {
               "DewPointC":"4",
               "DewPointF":"40",
               "FeelsLikeC":"3",
               "FeelsLikeF":"38",
               "HeatIndexC":"7",
               "HeatIndexF":"44",
               "WindChillC":"3",
               "WindChillF":"38",
               "WindGustKmph":"21",
               "WindGustMiles":"13",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"89",
               "chanceofrain":"0",
               "chanceofremdry":"90",
               "chanceofsnow":"0",
               "chanceofsunshine":"16",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"71",
               "diffRad":"106.7",
               "humidity":"86",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1016",
               "pressureInches":"30",
               "shortRad":"424.3",
               "tempC":"7",
               "tempF":"44",
               "time":"1200",
               "uvIndex":"3",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"193",
               "windspeedKmph":"18",
               "windspeedMiles":"11"
            },
            {
               "DewPointC":"6",
               "DewPointF":"42",
               "FeelsLikeC":"7",
               "FeelsLikeF":"45",
               "HeatIndexC":"10",
               "HeatIndexF":"50",
               "WindChillC":"7",
               "WindChillF":"45",
               "WindGustKmph":"22",
               "WindGustMiles":"14",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"43",
               "chanceofrain":"0",
               "chanceofremdry":"85",
               "chanceofsnow":"0",
               "chanceofsunshine":"70",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"58",
               "diffRad":"227.2",
               "humidity":"74",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1014",
               "pressureInches":"30",
               "shortRad":"578.2",
               "tempC":"10",
               "tempF":"50",
               "time":"1500",
               "uvIndex":"2",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"116",
               "weatherDesc":[
                  {
                     "value":"Partly Cloudy "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"194",
               "windspeedKmph":"19",
               "windspeedMiles":"12"
            },
            {
               "DewPointC":"6",
               "DewPointF":"43",
               "FeelsLikeC":"6",
               "FeelsLikeF":"43",
               "HeatIndexC":"9",
               "HeatIndexF":"48",
               "WindChillC":"6",
               "WindChillF":"43",
               "WindGustKmph":"21",
               "WindGustMiles":"13",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"82",
               "chanceofrain":"0",
               "chanceofremdry":"83",
               "chanceofsnow":"0",
               "chanceofsunshine":"19",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"85",
               "diffRad":"159.2",
               "humidity":"83",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1013",
               "pressureInches":"30",
               "shortRad":"347.6",
               "tempC":"9",
               "tempF":"48",
               "time":"1800",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"119",
               "weatherDesc":[
                  {
                     "value":"Cloudy "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"192",
               "windspeedKmph":"14",
               "windspeedMiles":"9"
            },
            {
               "DewPointC":"6",
               "DewPointF":"42",
               "FeelsLikeC":"3",
               "FeelsLikeF":"38",
               "HeatIndexC":"7",
               "HeatIndexF":"44",
               "WindChillC":"3",
               "WindChillF":"38",
               "WindGustKmph":"29",
               "WindGustMiles":"18",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"80",
               "chanceofrain":"0",
               "chanceofremdry":"80",
               "chanceofsnow":"0",
               "chanceofsunshine":"7",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"0.0",
               "humidity":"94",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1014",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"7",
               "tempF":"44",
               "time":"2100",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"SSW",
               "winddirDegree":"195",
               "windspeedKmph":"16",
               "windspeedMiles":"10"
            }
         ],
         "maxtempC":"11",
         "maxtempF":"52",
         "mintempC":"3",
         "mintempF":"37",
         "sunHour":"9.8",
         "totalSnow_cm":"0.0",
         "uvIndex":"1"
      },
      {
         "astronomy":[
            {
               "moon_illumination":"97",
               "moon_phase":"Waning Gibbous",
               "moonrise":"09:43 PM",
               "moonset":"07:49 AM",
               "sunrise":"07:04 AM",
               "sunset":"07:02 PM"
            }
         ],
         "avgtempC":"11",
         "avgtempF":"52",
         "date":"2025-03-16",
         "hourly":[
            {
               "DewPointC":"6",
               "DewPointF":"43",
               "FeelsLikeC":"4",
               "FeelsLikeF":"39",
               "HeatIndexC":"7",
               "HeatIndexF":"44",
               "WindChillC":"4",
               "WindChillF":"39",
               "WindGustKmph":"25",
               "WindGustMiles":"15",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"85",
               "chanceofrain":"0",
               "chanceofremdry":"88",
               "chanceofsnow":"0",
               "chanceofsunshine":"9",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"0.0",
               "humidity":"96",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1013",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"7",
               "tempF":"44",
               "time":"0",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"190",
               "windspeedKmph":"14",
               "windspeedMiles":"9"
            },
            {
               "DewPointC":"8",
               "DewPointF":"46",
               "FeelsLikeC":"5",
               "FeelsLikeF":"41",
               "HeatIndexC":"8",
               "HeatIndexF":"47",
               "WindChillC":"5",
               "WindChillF":"41",
               "WindGustKmph":"20",
               "WindGustMiles":"12",
               "chanceoffog":"2",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"84",
               "chanceofrain":"0",
               "chanceofremdry":"89",
               "chanceofsnow":"0",
               "chanceofsunshine":"8",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"0.0",
               "humidity":"98",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1012",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"8",
               "tempF":"47",
               "time":"300",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"200",
               "weatherDesc":[
                  {
                     "value":"Thundery outbreaks in nearby"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"189",
               "windspeedKmph":"13",
               "windspeedMiles":"8"
            },
            {
               "DewPointC":"10",
               "DewPointF":"49",
               "FeelsLikeC":"7",
               "FeelsLikeF":"45",
               "HeatIndexC":"10",
               "HeatIndexF":"49",
               "WindChillC":"7",
               "WindChillF":"45",
               "WindGustKmph":"25",
               "WindGustMiles":"15",
               "chanceoffog":"2",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"80",
               "chanceofrain":"0",
               "chanceofremdry":"84",
               "chanceofsnow":"0",
               "chanceofsunshine":"10",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"0.0",
               "humidity":"99",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1010",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"10",
               "tempF":"49",
               "time":"600",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"175",
               "windspeedKmph":"16",
               "windspeedMiles":"10"
            },
            {
               "DewPointC":"11",
               "DewPointF":"52",
               "FeelsLikeC":"9",
               "FeelsLikeF":"48",
               "HeatIndexC":"12",
               "HeatIndexF":"53",
               "WindChillC":"9",
               "WindChillF":"48",
               "WindGustKmph":"30",
               "WindGustMiles":"19",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"93",
               "chanceofrain":"0",
               "chanceofremdry":"84",
               "chanceofsnow":"0",
               "chanceofsunshine":"18",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"18.5",
               "humidity":"96",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1011",
               "pressureInches":"30",
               "shortRad":"30.6",
               "tempC":"12",
               "tempF":"53",
               "time":"900",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"186",
               "windspeedKmph":"23",
               "windspeedMiles":"14"
            },
            {
               "DewPointC":"12",
               "DewPointF":"54",
               "FeelsLikeC":"11",
               "FeelsLikeF":"52",
               "HeatIndexC":"13",
               "HeatIndexF":"56",
               "WindChillC":"11",
               "WindChillF":"52",
               "WindGustKmph":"35",
               "WindGustMiles":"22",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"86",
               "chanceofrain":"0",
               "chanceofremdry":"85",
               "chanceofsnow":"0",
               "chanceofsunshine":"7",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"48.4",
               "humidity":"93",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1011",
               "pressureInches":"30",
               "shortRad":"79.1",
               "tempC":"13",
               "tempF":"56",
               "time":"1200",
               "uvIndex":"1",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"188",
               "windspeedKmph":"29",
               "windspeedMiles":"18"
            },
            {
               "DewPointC":"13",
               "DewPointF":"55",
               "FeelsLikeC":"12",
               "FeelsLikeF":"54",
               "HeatIndexC":"14",
               "HeatIndexF":"57",
               "WindChillC":"12",
               "WindChillF":"54",
               "WindGustKmph":"36",
               "WindGustMiles":"22",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"86",
               "chanceofrain":"0",
               "chanceofremdry":"93",
               "chanceofsnow":"0",
               "chanceofsunshine":"16",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"53.1",
               "humidity":"92",
               "precipInches":"0.0",
               "precipMM":"0.0",
               "pressure":"1009",
               "pressureInches":"30",
               "shortRad":"82.1",
               "tempC":"14",
               "tempF":"57",
               "time":"1500",
               "uvIndex":"1",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"122",
               "weatherDesc":[
                  {
                     "value":"Overcast "
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"182",
               "windspeedKmph":"28",
               "windspeedMiles":"17"
            },
            {
               "DewPointC":"13",
               "DewPointF":"55",
               "FeelsLikeC":"12",
               "FeelsLikeF":"53",
               "HeatIndexC":"14",
               "HeatIndexF":"57",
               "WindChillC":"12",
               "WindChillF":"53",
               "WindGustKmph":"29",
               "WindGustMiles":"18",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"86",
               "chanceofrain":"100",
               "chanceofremdry":"0",
               "chanceofsnow":"0",
               "chanceofsunshine":"0",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"35.2",
               "humidity":"94",
               "precipInches":"0.0",
               "precipMM":"0.8",
               "pressure":"1008",
               "pressureInches":"30",
               "shortRad":"54.9",
               "tempC":"14",
               "tempF":"57",
               "time":"1800",
               "uvIndex":"0",
               "visibility":"9",
               "visibilityMiles":"5",
               "weatherCode":"299",
               "weatherDesc":[
                  {
                     "value":"Moderate rain at times"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"176",
               "windspeedKmph":"21",
               "windspeedMiles":"13"
            },
            {
               "DewPointC":"13",
               "DewPointF":"55",
               "FeelsLikeC":"12",
               "FeelsLikeF":"53",
               "HeatIndexC":"14",
               "HeatIndexF":"56",
               "WindChillC":"12",
               "WindChillF":"53",
               "WindGustKmph":"48",
               "WindGustMiles":"30",
               "chanceoffog":"0",
               "chanceoffrost":"0",
               "chanceofhightemp":"0",
               "chanceofovercast":"94",
               "chanceofrain":"100",
               "chanceofremdry":"0",
               "chanceofsnow":"0",
               "chanceofsunshine":"0",
               "chanceofthunder":"0",
               "chanceofwindy":"0",
               "cloudcover":"100",
               "diffRad":"0.0",
               "humidity":"97",
               "precipInches":"0.2",
               "precipMM":"5.0",
               "pressure":"1007",
               "pressureInches":"30",
               "shortRad":"0.0",
               "tempC":"14",
               "tempF":"56",
               "time":"2100",
               "uvIndex":"0",
               "visibility":"10",
               "visibilityMiles":"6",
               "weatherCode":"296",
               "weatherDesc":[
                  {
                     "value":"Light rain"
                  }
               ],
               "weatherIconUrl":[
                  {
                     "value":""
                  }
               ],
               "winddir16Point":"S",
               "winddirDegree":"182",
               "windspeedKmph":"30",
               "windspeedMiles":"19"
            }
         ],
         "maxtempC":"14",
         "maxtempF":"58",
         "mintempC":"6",
         "mintempF":"43",
         "sunHour":"9.0",
         "totalSnow_cm":"0.0",
         "uvIndex":"0"
      }
   ]
}
'''

def getWttrIn(zip):
    return json_decode(get(f'https://wttr.in/{zip}?format=j1').text)

def nextThreeDays(dct):
    for i, day in enumerate(dct['weather']):
        dayName = datetime.strptime(day['date'], '%Y-%m-%d').strftime('%A')
        if i == 0:
            dayName = 'Today'
        low = day['mintempF']
        high = day['maxtempF']
        yield t.div(
            t.div(style='height: 3rem; border-left: 1px solid black;'),
            t.h2(dayName),
            t.h4(day['hourly'][4]['weatherDesc'][0]['value']),
            t.h3(f'{high}&deg;F', style='color: red;'),
            t.h3(f'{low}&deg;F', style='color: blue;'),
            _class='flex-row flex-center flex-gap',
            )

class index(ControllerPublic):
    @returnAs(t.div, id='weather', **{'data-url': '/weather/weather'})
    def get(self):
        return page(
            headStuff=(
                t.script('setInterval(framework.process, 1000 * 60 * 15, "weather");'),
                ),
            bodyStuff=weather.getNow(),
            )

class weather(ControllerPublic):
    @returnAs(t.div, id='weather', **{'data-url': '/weather/weather'},
              style='margin-left: 2rem;')
    def get(self):
        dct = getWttrIn('05466')
        return t.div(
            t.pre(get('https://wttr.in/Ripton,VT?u&format=%l:+%c+%t+(%f)+%w+%h').text),
            nextThreeDays(dct),
            _class='flex-row flex-center flex-gap',
            )
