from lib.framework import ControllerPublic
from lib.framework import letAs
from lib.framework import returnAs
from lib.framework import stream
from lib.framework import t
import json
import os
import requests
import time

CACHE_DURATION = 20 * 60  # 20 minutes in seconds
ZIP = '05766'

def getConditions(zip_code=ZIP):
    """
    Retrieves current weather conditions for a given US zip code using wttr.in.
    The function caches the JSON response on disk and reuses it if it's less than 20 minutes old.

    Args:
        zip_code (str or int): The US zip code.

    Returns:
        dict: The current weather conditions extracted from wttr.in's JSON response.
    example:
{'current_condition': [{'FeelsLikeC': '-7',
                        'FeelsLikeF': '19',
                        'cloudcover': '0',
                        'humidity': '46',
                        'localObsDateTime': '2025-03-12 10:41 AM',
                        'observation_time': '02:41 PM',
                        'precipInches': '0.0',
                        'precipMM': '0.0',
                        'pressure': '1020',
                        'pressureInches': '30',
                        'temp_C': '-3',
                        'temp_F': '26',
                        'uvIndex': '2',
                        'visibility': '16',
                        'visibilityMiles': '9',
                        'weatherCode': '113',
                        'weatherDesc': [{'value': 'Sunny'}],
                        'weatherIconUrl': [{'value': ''}],
                        'winddir16Point': 'NNE',
                        'winddirDegree': '21',
                        'windspeedKmph': '10',
                        'windspeedMiles': '6'}],
 'nearest_area': [{'areaName': [{'value': 'Middlebury'}],
                   'country': [{'value': 'United States of America'}],
                   'latitude': '44.015',
                   'longitude': '-73.168',
                   'population': '8862',
                   'region': [{'value': 'Vermont'}],
                   'weatherUrl': [{'value': ''}]}],
 'request': [{'query': 'Lat 43.98 and Lon -73.01', 'type': 'LatLon'}],
 'weather': [{'astronomy': [{'moon_illumination': '95',
                             'moon_phase': 'Waxing Gibbous',
                             'moonrise': '05:27 PM',
                             'moonset': '06:40 AM',
                             'sunrise': '07:11 AM',
                             'sunset': '06:57 PM'}],
              'avgtempC': '-2',
              'avgtempF': '28',
              'date': '2025-03-12',
              'hourly': [{'DewPointC': '-1',
                          'DewPointF': '31',
                          'FeelsLikeC': '-2',
                          'FeelsLikeF': '29',
                          'HeatIndexC': '2',
                          'HeatIndexF': '35',
                          'WindChillC': '-2',
                          'WindChillF': '29',
                          'WindGustKmph': '23',
                          'WindGustMiles': '14',
                          'chanceoffog': '0',
                          'chanceoffrost': '99',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '0',
                          'chanceofrain': '0',
                          'chanceofremdry': '85',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '88',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '15',
                          'diffRad': '0.0',
                          'humidity': '82',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1010',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '2',
                          'tempF': '35',
                          'time': '0',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '113',
                          'weatherDesc': [{'value': 'Clear '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'N',
                          'winddirDegree': '355',
                          'windspeedKmph': '11',
                          'windspeedMiles': '7'},
                         {'DewPointC': '-6',
                          'DewPointF': '21',
                          'FeelsLikeC': '-9',
                          'FeelsLikeF': '16',
                          'HeatIndexC': '-3',
                          'HeatIndexF': '26',
                          'WindChillC': '-9',
                          'WindChillF': '16',
                          'WindGustKmph': '21',
                          'WindGustMiles': '13',
                          'chanceoffog': '0',
                          'chanceoffrost': '98',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '47',
                          'chanceofrain': '0',
                          'chanceofremdry': '89',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '75',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '39',
                          'diffRad': '0.0',
                          'humidity': '84',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1014',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '-3',
                          'tempF': '26',
                          'time': '300',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '116',
                          'weatherDesc': [{'value': 'Partly Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'NNE',
                          'winddirDegree': '19',
                          'windspeedKmph': '15',
                          'windspeedMiles': '9'},
                         {'DewPointC': '-8',
                          'DewPointF': '17',
                          'FeelsLikeC': '-11',
                          'FeelsLikeF': '12',
                          'HeatIndexC': '-5',
                          'HeatIndexF': '22',
                          'WindChillC': '-11',
                          'WindChillF': '12',
                          'WindGustKmph': '14',
                          'WindGustMiles': '8',
                          'chanceoffog': '0',
                          'chanceoffrost': '98',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '0',
                          'chanceofrain': '0',
                          'chanceofremdry': '83',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '94',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '3',
                          'diffRad': '0.0',
                          'humidity': '80',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1017',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '-5',
                          'tempF': '22',
                          'time': '600',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '113',
                          'weatherDesc': [{'value': 'Clear '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'NNE',
                          'winddirDegree': '26',
                          'windspeedKmph': '11',
                          'windspeedMiles': '7'},
                         {'DewPointC': '-10',
                          'DewPointF': '15',
                          'FeelsLikeC': '-10',
                          'FeelsLikeF': '14',
                          'HeatIndexC': '-4',
                          'HeatIndexF': '24',
                          'WindChillC': '-10',
                          'WindChillF': '14',
                          'WindGustKmph': '12',
                          'WindGustMiles': '8',
                          'chanceoffog': '0',
                          'chanceoffrost': '97',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '0',
                          'chanceofrain': '0',
                          'chanceofremdry': '85',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '92',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '21',
                          'diffRad': '52.2',
                          'humidity': '69',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '176.9',
                          'tempC': '-4',
                          'tempF': '24',
                          'time': '900',
                          'uvIndex': '1',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '113',
                          'weatherDesc': [{'value': 'Sunny'}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'NNE',
                          'winddirDegree': '21',
                          'windspeedKmph': '11',
                          'windspeedMiles': '7'},
                         {'DewPointC': '-10',
                          'DewPointF': '15',
                          'FeelsLikeC': '-5',
                          'FeelsLikeF': '23',
                          'HeatIndexC': '-2',
                          'HeatIndexF': '29',
                          'WindChillC': '-5',
                          'WindChillF': '23',
                          'WindGustKmph': '11',
                          'WindGustMiles': '7',
                          'chanceoffog': '0',
                          'chanceoffrost': '95',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '38',
                          'chanceofrain': '0',
                          'chanceofremdry': '87',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '71',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '44',
                          'diffRad': '104.6',
                          'humidity': '54',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '424.6',
                          'tempC': '-2',
                          'tempF': '29',
                          'time': '1200',
                          'uvIndex': '3',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '116',
                          'weatherDesc': [{'value': 'Partly Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'NNE',
                          'winddirDegree': '26',
                          'windspeedKmph': '9',
                          'windspeedMiles': '6'},
                         {'DewPointC': '-9',
                          'DewPointF': '16',
                          'FeelsLikeC': '-3',
                          'FeelsLikeF': '26',
                          'HeatIndexC': '-0',
                          'HeatIndexF': '32',
                          'WindChillC': '-3',
                          'WindChillF': '26',
                          'WindGustKmph': '11',
                          'WindGustMiles': '7',
                          'chanceoffog': '0',
                          'chanceoffrost': '51',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '89',
                          'chanceofrain': '0',
                          'chanceofremdry': '87',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '8',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '100',
                          'diffRad': '206.6',
                          'humidity': '48',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '404.8',
                          'tempC': '-0',
                          'tempF': '32',
                          'time': '1500',
                          'uvIndex': '2',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'NE',
                          'winddirDegree': '38',
                          'windspeedKmph': '10',
                          'windspeedMiles': '6'},
                         {'DewPointC': '-9',
                          'DewPointF': '16',
                          'FeelsLikeC': '-4',
                          'FeelsLikeF': '26',
                          'HeatIndexC': '-1',
                          'HeatIndexF': '30',
                          'WindChillC': '-4',
                          'WindChillF': '26',
                          'WindGustKmph': '9',
                          'WindGustMiles': '5',
                          'chanceoffog': '0',
                          'chanceoffrost': '92',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '89',
                          'chanceofrain': '0',
                          'chanceofremdry': '94',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '14',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '100',
                          'diffRad': '107.4',
                          'humidity': '55',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '203.1',
                          'tempC': '-1',
                          'tempF': '30',
                          'time': '1800',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'NNE',
                          'winddirDegree': '23',
                          'windspeedKmph': '8',
                          'windspeedMiles': '5'},
                         {'DewPointC': '-8',
                          'DewPointF': '17',
                          'FeelsLikeC': '-3',
                          'FeelsLikeF': '27',
                          'HeatIndexC': '-2',
                          'HeatIndexF': '28',
                          'WindChillC': '-3',
                          'WindChillF': '27',
                          'WindGustKmph': '5',
                          'WindGustMiles': '3',
                          'chanceoffog': '0',
                          'chanceoffrost': '91',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '87',
                          'chanceofrain': '0',
                          'chanceofremdry': '88',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '16',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '100',
                          'diffRad': '0.0',
                          'humidity': '62',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '-2',
                          'tempF': '28',
                          'time': '2100',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'N',
                          'winddirDegree': '6',
                          'windspeedKmph': '4',
                          'windspeedMiles': '2'}],
              'maxtempC': '1',
              'maxtempF': '33',
              'mintempC': '-6',
              'mintempF': '21',
              'sunHour': '9.5',
              'totalSnow_cm': '0.0',
              'uvIndex': '1'},
             {'astronomy': [{'moon_illumination': '98',
                             'moon_phase': 'Waxing Gibbous',
                             'moonrise': '06:32 PM',
                             'moonset': '06:59 AM',
                             'sunrise': '07:09 AM',
                             'sunset': '06:58 PM'}],
              'avgtempC': '1',
              'avgtempF': '34',
              'date': '2025-03-13',
              'hourly': [{'DewPointC': '-8',
                          'DewPointF': '18',
                          'FeelsLikeC': '-2',
                          'FeelsLikeF': '28',
                          'HeatIndexC': '-2',
                          'HeatIndexF': '28',
                          'WindChillC': '-2',
                          'WindChillF': '28',
                          'WindGustKmph': '3',
                          'WindGustMiles': '2',
                          'chanceoffog': '0',
                          'chanceoffrost': '90',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '82',
                          'chanceofrain': '0',
                          'chanceofremdry': '80',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '16',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '82',
                          'diffRad': '0.0',
                          'humidity': '67',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1019',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '-2',
                          'tempF': '28',
                          'time': '0',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '119',
                          'weatherDesc': [{'value': 'Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'N',
                          'winddirDegree': '9',
                          'windspeedKmph': '2',
                          'windspeedMiles': '1'},
                         {'DewPointC': '-7',
                          'DewPointF': '19',
                          'FeelsLikeC': '-2',
                          'FeelsLikeF': '28',
                          'HeatIndexC': '-2',
                          'HeatIndexF': '28',
                          'WindChillC': '-2',
                          'WindChillF': '28',
                          'WindGustKmph': '2',
                          'WindGustMiles': '1',
                          'chanceoffog': '0',
                          'chanceoffrost': '90',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '89',
                          'chanceofrain': '0',
                          'chanceofremdry': '94',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '9',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '66',
                          'diffRad': '0.0',
                          'humidity': '71',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1019',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '-2',
                          'tempF': '28',
                          'time': '300',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSE',
                          'winddirDegree': '167',
                          'windspeedKmph': '1',
                          'windspeedMiles': '1'},
                         {'DewPointC': '-6',
                          'DewPointF': '21',
                          'FeelsLikeC': '-2',
                          'FeelsLikeF': '28',
                          'HeatIndexC': '-1',
                          'HeatIndexF': '29',
                          'WindChillC': '-2',
                          'WindChillF': '28',
                          'WindGustKmph': '2',
                          'WindGustMiles': '1',
                          'chanceoffog': '0',
                          'chanceoffrost': '88',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '46',
                          'chanceofrain': '0',
                          'chanceofremdry': '83',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '88',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '36',
                          'diffRad': '0.0',
                          'humidity': '69',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '-1',
                          'tempF': '29',
                          'time': '600',
                          'uvIndex': '0',
                          'visibility': '5',
                          'visibilityMiles': '3',
                          'weatherCode': '116',
                          'weatherDesc': [{'value': 'Partly Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSE',
                          'winddirDegree': '168',
                          'windspeedKmph': '2',
                          'windspeedMiles': '1'},
                         {'DewPointC': '-5',
                          'DewPointF': '24',
                          'FeelsLikeC': '-0',
                          'FeelsLikeF': '31',
                          'HeatIndexC': '2',
                          'HeatIndexF': '35',
                          'WindChillC': '-0',
                          'WindChillF': '31',
                          'WindGustKmph': '5',
                          'WindGustMiles': '3',
                          'chanceoffog': '0',
                          'chanceoffrost': '27',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '40',
                          'chanceofrain': '0',
                          'chanceofremdry': '93',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '81',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '42',
                          'diffRad': '57.0',
                          'humidity': '62',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '113.4',
                          'tempC': '2',
                          'tempF': '35',
                          'time': '900',
                          'uvIndex': '1',
                          'visibility': '5',
                          'visibilityMiles': '3',
                          'weatherCode': '116',
                          'weatherDesc': [{'value': 'Partly Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSE',
                          'winddirDegree': '165',
                          'windspeedKmph': '5',
                          'windspeedMiles': '3'},
                         {'DewPointC': '-2',
                          'DewPointF': '28',
                          'FeelsLikeC': '1',
                          'FeelsLikeF': '33',
                          'HeatIndexC': '3',
                          'HeatIndexF': '38',
                          'WindChillC': '1',
                          'WindChillF': '33',
                          'WindGustKmph': '7',
                          'WindGustMiles': '4',
                          'chanceoffog': '0',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '31',
                          'chanceofrain': '0',
                          'chanceofremdry': '86',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '70',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '72',
                          'diffRad': '97.3',
                          'humidity': '64',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '184.7',
                          'tempC': '3',
                          'tempF': '38',
                          'time': '1200',
                          'uvIndex': '3',
                          'visibility': '5',
                          'visibilityMiles': '3',
                          'weatherCode': '116',
                          'weatherDesc': [{'value': 'Partly Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'S',
                          'winddirDegree': '171',
                          'windspeedKmph': '6',
                          'windspeedMiles': '4'},
                         {'DewPointC': '-2',
                          'DewPointF': '29',
                          'FeelsLikeC': '0',
                          'FeelsLikeF': '32',
                          'HeatIndexC': '3',
                          'HeatIndexF': '37',
                          'WindChillC': '0',
                          'WindChillF': '32',
                          'WindGustKmph': '6',
                          'WindGustMiles': '4',
                          'chanceoffog': '0',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '91',
                          'chanceofrain': '0',
                          'chanceofremdry': '89',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '10',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '100',
                          'diffRad': '40.3',
                          'humidity': '70',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '62.1',
                          'tempC': '3',
                          'tempF': '37',
                          'time': '1500',
                          'uvIndex': '1',
                          'visibility': '2',
                          'visibilityMiles': '1',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'S',
                          'winddirDegree': '185',
                          'windspeedKmph': '5',
                          'windspeedMiles': '3'},
                         {'DewPointC': '-3',
                          'DewPointF': '26',
                          'FeelsLikeC': '-1',
                          'FeelsLikeF': '31',
                          'HeatIndexC': '2',
                          'HeatIndexF': '36',
                          'WindChillC': '-1',
                          'WindChillF': '31',
                          'WindGustKmph': '8',
                          'WindGustMiles': '5',
                          'chanceoffog': '0',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '83',
                          'chanceofrain': '0',
                          'chanceofremdry': '88',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '9',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '100',
                          'diffRad': '37.6',
                          'humidity': '68',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '62.3',
                          'tempC': '2',
                          'tempF': '36',
                          'time': '1800',
                          'uvIndex': '0',
                          'visibility': '2',
                          'visibilityMiles': '1',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'S',
                          'winddirDegree': '188',
                          'windspeedKmph': '6',
                          'windspeedMiles': '4'},
                         {'DewPointC': '-3',
                          'DewPointF': '26',
                          'FeelsLikeC': '-1',
                          'FeelsLikeF': '30',
                          'HeatIndexC': '1',
                          'HeatIndexF': '34',
                          'WindChillC': '-1',
                          'WindChillF': '30',
                          'WindGustKmph': '8',
                          'WindGustMiles': '5',
                          'chanceoffog': '47',
                          'chanceoffrost': '10',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '87',
                          'chanceofrain': '0',
                          'chanceofremdry': '81',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '12',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '91',
                          'diffRad': '0.0',
                          'humidity': '71',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1022',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '1',
                          'tempF': '34',
                          'time': '2100',
                          'uvIndex': '0',
                          'visibility': '0',
                          'visibilityMiles': '0',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '200',
                          'windspeedKmph': '5',
                          'windspeedMiles': '3'}],
              'maxtempC': '5',
              'maxtempF': '40',
              'mintempC': '-3',
              'mintempF': '28',
              'sunHour': '9.3',
              'totalSnow_cm': '0.0',
              'uvIndex': '1'},
             {'astronomy': [{'moon_illumination': '100',
                             'moon_phase': 'Full Moon',
                             'moonrise': '07:36 PM',
                             'moonset': '07:16 AM',
                             'sunrise': '07:07 AM',
                             'sunset': '06:59 PM'}],
              'avgtempC': '2',
              'avgtempF': '36',
              'date': '2025-03-14',
              'hourly': [{'DewPointC': '-2',
                          'DewPointF': '28',
                          'FeelsLikeC': '-1',
                          'FeelsLikeF': '30',
                          'HeatIndexC': '1',
                          'HeatIndexF': '34',
                          'WindChillC': '-1',
                          'WindChillF': '30',
                          'WindGustKmph': '8',
                          'WindGustMiles': '5',
                          'chanceoffog': '2',
                          'chanceoffrost': '10',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '91',
                          'chanceofrain': '0',
                          'chanceofremdry': '82',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '17',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '90',
                          'diffRad': '0.0',
                          'humidity': '78',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1022',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '1',
                          'tempF': '34',
                          'time': '0',
                          'uvIndex': '0',
                          'visibility': '2',
                          'visibilityMiles': '1',
                          'weatherCode': '119',
                          'weatherDesc': [{'value': 'Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '192',
                          'windspeedKmph': '5',
                          'windspeedMiles': '3'},
                         {'DewPointC': '-2',
                          'DewPointF': '29',
                          'FeelsLikeC': '-1',
                          'FeelsLikeF': '30',
                          'HeatIndexC': '1',
                          'HeatIndexF': '33',
                          'WindChillC': '-1',
                          'WindChillF': '30',
                          'WindGustKmph': '7',
                          'WindGustMiles': '4',
                          'chanceoffog': '1',
                          'chanceoffrost': '10',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '82',
                          'chanceofrain': '0',
                          'chanceofremdry': '93',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '18',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '99',
                          'diffRad': '0.0',
                          'humidity': '85',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '1',
                          'tempF': '33',
                          'time': '300',
                          'uvIndex': '0',
                          'visibility': '2',
                          'visibilityMiles': '1',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '204',
                          'windspeedKmph': '4',
                          'windspeedMiles': '2'},
                         {'DewPointC': '-1',
                          'DewPointF': '30',
                          'FeelsLikeC': '-1',
                          'FeelsLikeF': '30',
                          'HeatIndexC': '1',
                          'HeatIndexF': '33',
                          'WindChillC': '-1',
                          'WindChillF': '30',
                          'WindGustKmph': '11',
                          'WindGustMiles': '7',
                          'chanceoffog': '17',
                          'chanceoffrost': '24',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '94',
                          'chanceofrain': '0',
                          'chanceofremdry': '91',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '6',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '100',
                          'diffRad': '0.0',
                          'humidity': '89',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '1',
                          'tempF': '33',
                          'time': '600',
                          'uvIndex': '0',
                          'visibility': '2',
                          'visibilityMiles': '1',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '195',
                          'windspeedKmph': '6',
                          'windspeedMiles': '4'},
                         {'DewPointC': '-0',
                          'DewPointF': '31',
                          'FeelsLikeC': '0',
                          'FeelsLikeF': '32',
                          'HeatIndexC': '2',
                          'HeatIndexF': '35',
                          'WindChillC': '0',
                          'WindChillF': '32',
                          'WindGustKmph': '8',
                          'WindGustMiles': '5',
                          'chanceoffog': '0',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '89',
                          'chanceofrain': '0',
                          'chanceofremdry': '93',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '12',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '92',
                          'diffRad': '51.4',
                          'humidity': '84',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1022',
                          'pressureInches': '30',
                          'shortRad': '201.2',
                          'tempC': '2',
                          'tempF': '35',
                          'time': '900',
                          'uvIndex': '1',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'S',
                          'winddirDegree': '185',
                          'windspeedKmph': '7',
                          'windspeedMiles': '4'},
                         {'DewPointC': '1',
                          'DewPointF': '33',
                          'FeelsLikeC': '1',
                          'FeelsLikeF': '34',
                          'HeatIndexC': '4',
                          'HeatIndexF': '39',
                          'WindChillC': '1',
                          'WindChillF': '34',
                          'WindGustKmph': '13',
                          'WindGustMiles': '8',
                          'chanceoffog': '0',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '88',
                          'chanceofrain': '0',
                          'chanceofremdry': '81',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '6',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '84',
                          'diffRad': '71.0',
                          'humidity': '78',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1021',
                          'pressureInches': '30',
                          'shortRad': '449.6',
                          'tempC': '4',
                          'tempF': '39',
                          'time': '1200',
                          'uvIndex': '4',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '119',
                          'weatherDesc': [{'value': 'Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'S',
                          'winddirDegree': '188',
                          'windspeedKmph': '11',
                          'windspeedMiles': '7'},
                         {'DewPointC': '2',
                          'DewPointF': '36',
                          'FeelsLikeC': '2',
                          'FeelsLikeF': '36',
                          'HeatIndexC': '4',
                          'HeatIndexF': '40',
                          'WindChillC': '2',
                          'WindChillF': '36',
                          'WindGustKmph': '15',
                          'WindGustMiles': '9',
                          'chanceoffog': '0',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '92',
                          'chanceofrain': '0',
                          'chanceofremdry': '83',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '16',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '87',
                          'diffRad': '216.4',
                          'humidity': '84',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1020',
                          'pressureInches': '30',
                          'shortRad': '575.9',
                          'tempC': '4',
                          'tempF': '40',
                          'time': '1500',
                          'uvIndex': '3',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '119',
                          'weatherDesc': [{'value': 'Cloudy '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '192',
                          'windspeedKmph': '13',
                          'windspeedMiles': '8'},
                         {'DewPointC': '3',
                          'DewPointF': '37',
                          'FeelsLikeC': '1',
                          'FeelsLikeF': '35',
                          'HeatIndexC': '4',
                          'HeatIndexF': '39',
                          'WindChillC': '1',
                          'WindChillF': '35',
                          'WindGustKmph': '12',
                          'WindGustMiles': '7',
                          'chanceoffog': '2',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '90',
                          'chanceofrain': '0',
                          'chanceofremdry': '89',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '6',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '90',
                          'diffRad': '145.6',
                          'humidity': '92',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1019',
                          'pressureInches': '30',
                          'shortRad': '393.9',
                          'tempC': '4',
                          'tempF': '39',
                          'time': '1800',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '122',
                          'weatherDesc': [{'value': 'Overcast '}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '204',
                          'windspeedKmph': '8',
                          'windspeedMiles': '5'},
                         {'DewPointC': '3',
                          'DewPointF': '37',
                          'FeelsLikeC': '1',
                          'FeelsLikeF': '34',
                          'HeatIndexC': '3',
                          'HeatIndexF': '38',
                          'WindChillC': '1',
                          'WindChillF': '34',
                          'WindGustKmph': '16',
                          'WindGustMiles': '10',
                          'chanceoffog': '2',
                          'chanceoffrost': '0',
                          'chanceofhightemp': '0',
                          'chanceofovercast': '83',
                          'chanceofrain': '0',
                          'chanceofremdry': '92',
                          'chanceofsnow': '0',
                          'chanceofsunshine': '9',
                          'chanceofthunder': '0',
                          'chanceofwindy': '0',
                          'cloudcover': '95',
                          'diffRad': '0.0',
                          'humidity': '97',
                          'precipInches': '0.0',
                          'precipMM': '0.0',
                          'pressure': '1019',
                          'pressureInches': '30',
                          'shortRad': '0.0',
                          'tempC': '3',
                          'tempF': '38',
                          'time': '2100',
                          'uvIndex': '0',
                          'visibility': '10',
                          'visibilityMiles': '6',
                          'weatherCode': '143',
                          'weatherDesc': [{'value': 'Mist'}],
                          'weatherIconUrl': [{'value': ''}],
                          'winddir16Point': 'SSW',
                          'winddirDegree': '203',
                          'windspeedKmph': '8',
                          'windspeedMiles': '5'}],
              'maxtempC': '5',
              'maxtempF': '41',
              'mintempC': '1',
              'mintempF': '33',
              'sunHour': '8.3',
              'totalSnow_cm': '0.0',
              'uvIndex': '1'}]}

    Raises:
        Exception: If the HTTP request fails.
    """
    # Create a unique cache filename for the zip code
    cache_file = f"wttr_{zip_code}.json"

    # Check if cache exists and is still valid
    if os.path.exists(cache_file):
        last_modified = os.path.getmtime(cache_file)
        print('!!!' * 10)
        print(time.time() - last_modified, CACHE_DURATION)
        if time.time() - last_modified < CACHE_DURATION:
            with open(cache_file, "r") as f:
                data = json.load(f)
            # wttr.in returns current conditions in a list; we use the first item.
            return data

    # If no valid cache, fetch fresh data from wttr.in
    url = f"http://wttr.in/{zip_code}?format=j1"
    response = requests.get(url)

    if response.status_code != 200:
        raise Exception(f"Error fetching data from wttr.in: HTTP {response.status_code}")

    data = response.json()

    # Write the fresh data to disk for caching
    with open(cache_file, "w") as f:
        json.dump(data, f)

    return data

def getCurrentTemp():
    conditions = getConditions()
    return conditions['temp_F']

class weather(ControllerPublic):
    if 'weather' not in stream.announcer.timeDict:
        stream.announcer.timeDict['weather'] = 10
    @returnAs(t.div, id='weather', **{'data-url': '/weather/weather'},
              _class='flex-col-stretch flex-gap')
    def get(self):
        yield t.style(
            '''
            table.weather td {
                    padding: 0.5em;
                    padding-top: 0;
            };
            ''')
        from datetime import datetime
        conditions = getConditions()
        for index, day in enumerate(conditions['weather']):
            date = day['date']
            dayName = datetime.strptime(date, '%Y-%m-%d').strftime('%A')
            today = ' (Today) ' if index == 0 else ''
            maxTemp = day['maxtempF']
            minTemp = day['mintempF']
            description = day['hourly'][0]['weatherDesc'][0]['value']
            sunrise = day['astronomy'][0]['sunrise']
            sunset = day['astronomy'][0]['sunset']
            humidity = day['hourly'][0]['humidity']
            windSpeed = day['hourly'][0]['windspeedMiles']
            windGust = day['hourly'][0]['WindGustMiles']
            emojWater = '&#128167;'
            emojSunr = '&#x1F305;'
            emojWind = '&#x1F4A8;'
            sunr = datetime.strptime(sunrise, '%I:%M %p')
            suns = datetime.strptime(sunset, '%I:%M %p')
            daylen = (suns - sunr).seconds // 60
            dayH = daylen // 60
            dayM = daylen % 60
            yield t.div(
                t.b(dayName,
                    today,
                    ' - ',
                    f'{description} (High: {maxTemp}&deg;F, Low: {minTemp}&deg;F)',
                    ),
                t.i(
                    emojSunr,
                    f' {sunr.strftime("%-I:%M %p")}',
                    ' - ',
                    f'{suns.strftime("%-I:%M %p")}',
                    f' ({dayH}h {dayM}m)',
                    ' ',
                    emojWind,
                    f' {windSpeed}',
                    f' - {windGust}' if windGust > windSpeed else '',
                    ' mph ',
                    emojWater,
                    f' {humidity}%',
                    ),
                _class='flex-col',
                )
            @letAs(t.div)
            @letAs(t.table, _class='weather')
            def hourly():
                for hour in day['hourly']:
                    time = hour['time']
                    if time in ('0', '300', '2100'):
                        continue
                    # convert to 12-hour time
                    dt = datetime.strptime('0000' if time == '0' else time, '%H%M')
                    timeText = dt.strftime('%-I:%M %p')
                    temp = hour['tempF']
                    description = hour['weatherDesc'][0]['value']
                    def getText(description, temp):
                        return f'{description} ({temp}&deg;F)'
                    yield t.tr(
                        t.td(timeText, style='text-align: right'),
                        t.td(description),
                        t.td(temp, '&deg;F', style='text-align: right'),
                        )
            yield hourly
